### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by Aqt1a** [iskandarov-egor/mandelset#3]
Hi thank you for your time. I really like your viewer, it is one of the best I have seen, but recently I found that the website won't load. I'm not sure if this is my system's fault or something else. Just letting you know and hoping it comes back. ~Aqtia

**Comment by iskandarov-egor** [comment]
hi, thanks for letting me know! website should be working now. glad you liked it!

http://mandelset.ru

**Comment by Aqt1a** [comment]
Thanks a lot! Love your work!
